// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database_util

import (
	"time"
)

type Item struct {
	ID          string
	Description string
	Price       float64
	Receipt     string
}

type Receipt struct {
	ID               string
	Retailer         string
	PurchaseDatetime time.Time
	Total            float64
}
