// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database_util

import (
	"time"

	"github.com/google/uuid"
)

type Item struct {
	ID          uuid.UUID
	Description string
	Price       string
	Receipt     uuid.UUID
}

type Receipt struct {
	ID               uuid.UUID
	Retailer         string
	PurchaseDatetime time.Time
	Total            string
}
