// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: receipts.sql

package database_util

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createReceipt = `-- name: CreateReceipt :one

INSERT INTO receipts
    (id, retailer, purchase_datetime, total)
VALUES
    ($1, $2, $3, $4)
RETURNING id, retailer, purchase_datetime, total
`

type CreateReceiptParams struct {
	ID               uuid.UUID
	Retailer         string
	PurchaseDatetime time.Time
	Total            string
}

func (q *Queries) CreateReceipt(ctx context.Context, arg CreateReceiptParams) (Receipt, error) {
	row := q.db.QueryRowContext(ctx, createReceipt,
		arg.ID,
		arg.Retailer,
		arg.PurchaseDatetime,
		arg.Total,
	)
	var i Receipt
	err := row.Scan(
		&i.ID,
		&i.Retailer,
		&i.PurchaseDatetime,
		&i.Total,
	)
	return i, err
}

const getReceipt = `-- name: GetReceipt :one
SELECT id, retailer, purchase_datetime, total FROM receipts where id=$1 LIMIT 1
`

func (q *Queries) GetReceipt(ctx context.Context, id uuid.UUID) (Receipt, error) {
	row := q.db.QueryRowContext(ctx, getReceipt, id)
	var i Receipt
	err := row.Scan(
		&i.ID,
		&i.Retailer,
		&i.PurchaseDatetime,
		&i.Total,
	)
	return i, err
}
